# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  links:
    - redis
  volumes:
    - ./:/usr/src/app
  ports:
    - 3030:3000
  environment:
    - PORT=3000
    - REDIS_URL=redis://cache
  command:
    sh -c 'node httpsServer.js'