# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  links:
    - redis
  volumes:
    - ./:/usr/src/app
  ports:
    - 3030:3000
  environment:
    - PORT=3000
    - REDIS_URL=redis://cache
  command:
    sh -c 'node app.js'

letsencrypt:
  image: linuxserver/letsencrypt
  container_name: letsencrypt
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./config/letsencrypt:/config
  environment:
    - EMAIL=filberttt@hotmail.com
    - URL=curly-lamp-server.fildabert.com
    - VALIDATION=http
    - PUID=1000
    - PGID=1000
